#cloud-config

hostname: os-load-generation
fqdn: os-load-generation

write_files:
  - path: /etc/sysctl.d/99-custom.conf
    content: |
      vm.max_map_count=262144
    owner: root:root
    permissions: '0644'
  - path: /load_generation.sh
    encoding: gz+b64
    content: ${load_script}
    owner: root:root
    permissions: '0755'
  - path: /fix_files.sh
    encoding: gz+b64
    content: ${fix_files_script}
    owner: root:root
    permissions: '0755'
  - path: /os_files/osb-1.11.0-knn.patch
    encoding: gz+b64
    content: |
      ${osb_knn_patch}
    owner: root:root
    permissions: '0644'
  - path: /os_files/vectorsearch-task.patch
    encoding: gz+b64
    content: |
      ${vectorsearch_task_patch}
    owner: root:root
    permissions: '0644'
  - path: /id_rsa
    encoding: gz+b64
    content: ${ssh_private_key}
    owner: root:root
    permissions: '0600'
  - path: /utils.sh
    encoding: gz+b64
    content: |
      ${utils_script}
    owner: root:root
    permissions: '0600'

fs_setup:
  - label: None
    filesystem: xfs
    device: /dev/nvme1n1
    partition: none
    overwrite: true

mounts:
  - [ /dev/nvme1n1, /mnt, xfs, "defaults", "0", "0" ]

bootcmd:
  - timeout 30s sh -c 'while [ ! -e /dev/nvme1n1 ]; do sleep 1; done'
  - swapoff -a

byobu_by_default: enable-user

package_update: true
packages:
  - pbzip2
  - jq
  - python3-pip
  - python3-venv
  - git
  - openjdk-17-jdk-headless

runcmd:
  - [ sysctl, -p, /etc/sysctl.d/99-custom.conf ]
  - [ chown, -R, ubuntu:ubuntu, /mnt ]
  - [ mv, /id_rsa, /home/ubuntu/.ssh/id_rsa ]
  - [ chown, ubuntu:ubuntu, /home/ubuntu/.ssh/id_rsa ]
  - [ mv, /utils.sh, /mnt/utils.sh ]
  - [ chown, ubuntu:ubuntu, /mnt/utils.sh ]
  - [ sudo, -u, ubuntu, /load_generation.sh, ${os_cluster}, admin, ${os_password}, ${distribution_version}, ${os_version}, "OS", ${instance_type}, ${cluster_instance_id}]
  - [ sudo, -u, ubuntu, /fix_files.sh ]
  - [sed, -i, '/^env.name =/c\env.name = ${benchmark_environment}', /mnt/.osb/benchmark.ini]
  - [sed, -i, '/^datastore\./s/^/# /',  /mnt/.osb/benchmark.ini]
  - |
    sed -i '/^\[results_publishing\]/a\
    # config using remote data store\
    datastore.type = opensearch\
    datastore.host = ${datastore_host}\
    datastore.port = 443\
    datastore.secure = True\
    datastore.ssl.verification_mode = none\
    datastore.user = ${datastore_username}\
    datastore.password = ${datastore_password}\
    datastore.number_of_replicas = 1\
    datastore.number_of_shards = 3\
    # default config using local memory data store' /mnt/.osb/benchmark.ini
