#cloud-config

hostname: es-cluster
fqdn: es-cluster

write_files:
  - path: /etc/sysctl.d/99-custom.conf
    content: |
      vm.max_map_count=262144
    owner: root:root
    permissions: '0644'
  - path: /es_cluster.sh
    encoding: gz+b64
    content: ${es_cluster_script}
    owner: root:root
    permissions: '0755'

fs_setup:
  - label: None
    filesystem: xfs
    device: /dev/nvme1n1
    partition: none
    overwrite: true

mounts:
  - [ /dev/nvme1n1, /mnt, xfs, "defaults", "0", "0" ]

bootcmd:
  - swapoff -a
  - ufw allow 9200/tcp
  - ufw allow 9300/tcp

runcmd:
  - [ sysctl, -p, /etc/sysctl.d/99-custom.conf ]
  - [ chown, -R, ubuntu:ubuntu, /mnt ]
  - [ sudo, -u, ubuntu, /es_cluster.sh, ${es_password}, ${es_snapshot_access_key}, ${es_snapshot_secret_key} ]
