#cloud-config

hostname: ${node_name}
fqdn: ${node_name}

write_files:
  - path: /etc/sysctl.d/99-custom.conf
    content: |
      vm.max_map_count=262144
    owner: root:root
    permissions: '0644'
  - path: /es_cluster.sh
    encoding: gz+b64
    content: |
      ${es_cluster_script}
    owner: root:root
    permissions: '0755'
  - path: /jvm.options
    encoding: gz+b64
    content: |
      ${jvm_options}
    owner: root:root
    permissions: '0644'
  - path: /ssh_pub_key
    encoding: gz+b64
    content: |
      ${authorized_ssh_key}
    owner: root:root
    permissions: '0644'
  - path: /es-cert.key
    encoding: gz+b64
    content: |
      ${crt_key}
    owner: root:root
    permissions: '0400'
  - path: /es-cert.crt
    encoding: gz+b64
    content: |
      ${crt}
    owner: root:root
    permissions: '0644'

fs_setup:
  - label: None
    filesystem: xfs
    device: /dev/nvme1n1
    partition: none
    overwrite: true

mounts:
  - [ /dev/nvme1n1, /mnt, xfs, "defaults", "0", "0" ]

bootcmd:
  - timeout 30s sh -c 'while [ ! -e /dev/nvme1n1 ]; do sleep 1; done'
  - swapoff -a
  - ufw allow 9200/tcp
  - ufw allow 9300/tcp

package_update: true
packages:
  - unzip

runcmd:
  - [ sysctl, -p, /etc/sysctl.d/99-custom.conf ]
  - [ chown, -R, ubuntu:ubuntu, /mnt ]
  - [ mv, /ssh_pub_key, /home/ubuntu/.ssh/authorized_keys ]
  - [ chown, ubuntu:ubuntu, /home/ubuntu/.ssh/authorized_keys ]
  - [ mv, /jvm.options, /mnt/jvm.options ]
  - [ chown, ubuntu:ubuntu, /mnt/jvm.options ]
  - [ chown, ubuntu:ubuntu, /es-cert.key ]
  - [ chown, ubuntu:ubuntu, /es-cert.crt ]
  - [ sudo, -u, ubuntu, /es_cluster.sh, "${es_password}", "${es_version}", "${es_arch}", "${es_snapshot_access_key}", "${es_snapshot_secret_key}", "${cluster_ips}", "${node_name}", "${nodes_type}" ]
