#cloud-config

hostname: es-load-generation
fqdn: es-load-generation

write_files:
  - path: /etc/sysctl.d/99-custom.conf
    content: |
      vm.max_map_count=262144
    owner: root:root
    permissions: '0644'
  - path: /load_generation.sh
    encoding: gz+b64
    content: ${load_script}
    owner: root:root
    permissions: '0755'
  - path: /fix_index.sh
    encoding: gz+b64
    content: ${fix_index_script}
    owner: root:root
    permissions: '0755'
  - path: /es_indexes/big5/es_index_8.15.0.json
    encoding: gz+b64
    content: |
      ${big5_es_index_8_15_0}
    owner: root:root
    permissions: '0644'
  - path: /benchmark.sh
    encoding: gz+b64
    content: ${benchmark_script}
    owner: root:root
    permissions: '0755'
  - path: /ingest.sh
    encoding: gz+b64
    content: ${ingest_script}
    owner: root:root
    permissions: '0755'
  - path: /restore_snapshot.sh
    encoding: gz+b64
    content: ${restore_snapshot_script}
    owner: root:root
    permissions: '0755'
  - path: /utils.sh
    encoding: gz+b64
    content: ${utils_script}
    owner: root:root
    permissions: '0755'

fs_setup:
  - label: None
    filesystem: xfs
    device: /dev/nvme1n1
    partition: none
    overwrite: true

mounts:
  - [ /dev/nvme1n1, /mnt, xfs, "defaults", "0", "0" ]

bootcmd:
  - swapoff -a

byobu_by_default: enable-user

package_update: true
packages:
  - pbzip2
  - jq
  - python3-pip
  - python3-venv
  - git
  - openjdk-17-jdk-headless

runcmd:
  - [ sysctl, -p, /etc/sysctl.d/99-custom.conf ]
  - [ chown, -R, ubuntu:ubuntu, /mnt ]
  - [ sudo, -u, ubuntu, /load_generation.sh, https://${es_cluster}:9200, elastic, ${es_password}, ${es_version}, "ES", ${instance_type}]
  - [ sudo, -u, ubuntu, /fix_index.sh, https://${es_cluster}:9200, elastic, ${es_password} ]
  - [sed, -i, '/^env.name =/c\env.name = ${benchmark_environment}', /mnt/.benchmark/benchmark.ini]
  - [sed, -i, '/^datastore\./s/^/# /',  /mnt/.benchmark/benchmark.ini]
  - |
    sed -i '/^\[results_publishing\]/a\
    # config using remote data store\
    datastore.type = opensearch\
    datastore.host = ${datastore_host}\
    datastore.port = 443\
    datastore.secure = True\
    datastore.ssl.verification_mode = none\
    datastore.user = ${datastore_username}\
    datastore.password = ${datastore_password}\
    datastore.number_of_replicas = 1\
    datastore.number_of_shards = 3\
    # default config using local memory data store' /mnt/.benchmark/benchmark.ini
