---
name: Nightly Benchmarks

permissions:
  contents: read

on:
  schedule:
    # Run every day at 00:00
    - cron: "0 0 * * *"

jobs:
  big5:
    uses: ./.github/workflows/big5-benchmark.yml
# nyc_taxis:
#   uses: ./.github/workflows/nyc_taxis.yml
# pmc:
#   uses: ./.github/workflows/pmc-benchmark.yml
# noaa:
#   uses: ./.github/workflows/noaa-benchmark.yml