#
# Copyright (c) 2024-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Linux

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  lint-report-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: infra/scripts/report-gen/pyproject.toml

      - name: install uv
        run: >
          curl --no-progress-meter --location --fail
          --proto '=https' --tlsv1.2
          "https://astral.sh/uv/install.sh"
          | sh

      - name: lint
        working-directory: ./infra/scripts/report-gen
        run: make lint INSTALL_EXTRA=lint
    
  
  shellcheck:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04]

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get install -y \
          shellcheck

    - name: Run ShellCheck (warnings only)
      run: |
        shellcheck --shell=bash --severity=warning --source-path="infra/scripts" $(find ./infra/scripts -type f -name '*.sh' | xargs)

    - name: Run ShellCheck
      continue-on-error: true
      run: |
        shellcheck --shell=bash --source-path="infra/scripts" $(find ./infra/scripts -type f -name '*.sh' | xargs)
